### ISSUE TITLE
Does generic-lens help backprop?

### ISSUE THREAD

**Issue by vincent-hui** [mstksg/backprop#11]
Just a simple thought.  Is using [generic-lens](https://github.com/kcsongor/generic-lens) beneficial to backprop?
I don't have an answer.

**Comment by mstksg** [comment]
It seems like it's useful for *making* the lenses that you can use :)  Otherwise I think it's the same situation as using template haskell-based lenses.  Maybe it might be worth suggesting as a solution for making lenses, instead of using template haskell.  However, I do suspect that generics-based lenses might necessarily be less performant than template haskell-based lenses, since generics requires O(n) field access, while template-haskell is O(1).

**Comment by mstksg** [comment]
Not closing this to say that the previous reply was a final word; just cleaning up some of the issues :)  Feel free to continue discussion.
