### ISSUE TITLE
Op between different types 

### ISSUE THREAD

**Issue by fabianmurariu** [mstksg/backprop#12]
Big fan of your work, I'm trying to understand/port backprop to Scala in https://github.com/fabianmurariu/ad4s 

I'm curious if you've come across the issue of operations in between types such as `Matrix / Double` where the type of Op [Matrix,Double] is (Matrix, Matrix => [Matrix,Double]) however because you're returning product when you multiply Matrix with Double you get Matrix back. 

For example (pardon my Haskell, I can barely read it)
```
-- | 'Op' for division
(/.) :: Matrix a Fractional b Matrix c => Op '[a, b] c
(/.) = op2 $ \x y -> (x / y, \g -> (g/y, -g*x/(y*y)))
```
The types don't alight because g/y and -g*x/(y*y) are all [Matrix, Matrix] but you expect [Matrix, Fractional]

**Comment by mstksg** [comment]
Hi Fabian; thank you for the kind words.

Yeah, the issue here is a little subtle, when you are defining your own gradients.  I have a [write-up on it](https://backprop.jle.im/06-manual-gradients.html) as a reference, but it still can be a bit tricky admittedly.

The reason why it's a single `Double` is because of how derivatives work.  If we have:

    f(x) = y

and we imagine a final result as a scalar:

    z = g(y) = g(f(x))

if `y` is a *matrix*, then we have to consider dz/dy1, dz/dy2, dz/dy3, dz/dy4... etc.

And so the gradient part of the `Op` is the function that, given dz/dy1, dz/dy2, dz/dy3, etc., returns dz/dx.

We have to think "how does z vary, as x varies?"  If we "tweak" x, how does it affect z?

Luckily for us, derivatives are linear!  So that means we can take advantage of a nice trick: we can compute the *total* that variation of x affects the variation of z by *adding together* the variations from y1, y2, y3, y4, etc.

So `dz/dx` is:

    dz/dx = dz/dy1 * dy1/dx
          + dz/dy2 * dy2/dx
          + dz/dy3 * dy3/dx
          + dz/dy4 * dy4/dx
          + ... etc


So to get the *total* amount that variation of your input parameter affects the "final" output, you have to sum together all of the contributions that go into the final output "via" all of the components in the matrix.  In other words, close to what you already have...but just the sum.

**Comment by fabianmurariu** [comment]
I think I got this, I need to sum the entire expression down to the same shape as the input, if it's a vector I sum on one of the axis and if it's a scalar I sum all the variations.

Thanks
