### ISSUE TITLE
What's the strategy for functions with no gradient?

### ISSUE THREAD

**Issue by fabianmurariu** [mstksg/backprop#14]
autograd has a few functions with no gradient
https://github.com/HIPS/autograd/blob/e3b525302529d7490769d5c0bcfc7457e24e3b3e/autograd/numpy/numpy_vjps.py#L14

noGrad Op seems to blowup when used so how does one interact with functions that do not have a gradient, floor and ceil come to mind but that is a large list over at autograd?

If you don't remember I'm the guy trying to copy your work into Scala https://github.com/fabianmurariu/ad4s

**Comment by mstksg** [comment]
For functions with an undefined gradient, `gradBP` should really be undefined.  For some functions, though, like `floor` and `ceil`, their gradients are defined *almost* everywhere on their domain, with discontinuities at the integers, so they would make sense as partial functions; they aren't currently implemented in *backprop*, but it's possible that they could be if a sensible `RealFrac` instance could be written.

We do "cheat" a bit.  For example, we allow `==` on BVars, which essentially makes equality a differentiable function, allowing us to write functions like reLU without manually specifying gradients.

This is in part possible because the architecture of *backprop* is slightly different from other libraries.  The differentiation graph is actually generated *dynamically*, for different inputs.  The entire graph is re-constructed from scratch for different inputs -- so, for different inputs, we get a different "shape" of graph.  Using `==` essentially forks the logic into two potential graphs; for inputs where things are equal, we generate a completely different graph than when the inputs where things are not equal.

This is a somewhat major source of overhead, but it does give us a method to differentiate `==`.

There is actually another method to differentiate `==` with a static graph, which is to account for both possible results within the Wengert tape itself.  However, doing this requires reifying things like case statements, which makes the library a bit harder to use without something like -XRebindableSyntax to redefine what if/then/else means.

So, this does allow us to differentiate functions like `==`, which makes our "no-grad" list a bit shorter than the autograd list.

For "truly" non-differentiable functions, there isn't really any other possible solution other than making `gradBP` be partial, I think -- it matches the semantics as well as possible.

**Comment by mstksg** [comment]
Small unrelated comment to elaborate on the previous post: it should also be noted that profiling reveals that the construction of the differentiation graph is only a small % of the total runtime of gradient computation.  while we do have the ability to shave off a few % points by switching to a static graph, loosing the ability to easily do branching gradients on `==` might not be worth it.
